name: Daily snapshots

on:
  schedule:
    - cron: "23 9 * * *"     # daily 09:23 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Run snapshot crawler
        run: npm run snapshot

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Rebase on latest tip
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git fetch origin "$BRANCH"
          git checkout "$BRANCH"
          git pull --rebase origin "$BRANCH" || true

      - name: Commit snapshot changes (if any)
        run: |
          if [[ -n $(git status --porcelain snapshots) ]]; then
            git add snapshots
            git commit -m "Daily site snapshots" || echo "Nothing to commit."
          else
            echo "No snapshot changes."
          fi

      - name: Push (with lease)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          # Use --force-with-lease to avoid non-fast-forward failures but still be safe.
          git push --force-with-lease origin "$BRANCH"
